### ISSUE TITLE
line numbers for yaml and/or json errors

### ISSUE THREAD

**Issue by fredkgit** [Orange-OpenSource/Cloudnet-TOSCA-toolbox#17] opened 2020-11-27 07:44 UTC
Some errors due to, e.g. indentation, or empty assignment, lead to errors like "None is not of type object ", or "None is not valid under the given schema". It's sometimes really tricky to find them, especially in templates of hundreds or thousands of lines.
Isn't there some way to help the user find the error location?

**Comment by philippemerle** [comment] 2020-11-27 09:40
Unfortunately, I don't see how to indicate the line for these errors.
The parsing of a yaml file (yaml.load) produces a Python dict, which does not contain line information.
Then this dict is checked against the YAML/JSON schema.
These errors are produced by the JSON schema checker, which does not know lines.

**Comment by philippemerle** [comment] 2020-11-27 10:17
The JSON schema validator can not indicate line numbers but the validator could indicate the path of the invalid yaml element. So this could be a way to indicate where errors are.

**Comment by philippemerle** [comment] 2020-11-27 13:11
@fredkgit: could you check that the issue is resolved by commits https://github.com/Orange-OpenSource/Cloudnet-TOSCA-toolbox/commit/36fd7509f499c975489cba525314ca7e3bbfab86?

**Comment by fredkgit** [comment] 2020-11-27 15:45
Tested with success. It's much easier to locate the error, now.
Thank you!

**Comment by fredkgit** [comment] 2020-11-27 16:09
I see you opened Jean-Luc's pull request on the same subject, so reopen the issue.

**Comment by JLCoulin** [comment] 2020-11-30 09:20
Hello guys, 
Sorry to be late, but what do we decide to implement ?

The pyyaml packet already test the yaml validity of the loaded file.

Don't you think it's simpler to test the return code of the yaml.load function than creating a special code for that ?

**Closed** 2021-04-19 09:11 UTC
Labels: enhancement
